# Generated by Django 5.0.1 on 2024-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "open"),
                    ("ONGOING", "ongoing"),
                    ("RESOLVED", "resolved"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
