# Generated by Django 5.0.1 on 2024-01-23 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_conversation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.agent",
            ),
        ),
    ]
