# Generated by Django 5.0.1 on 2024-01-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_conversation_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="agent",
        ),
        migrations.AddField(
            model_name="conversation",
            name="agent_active",
            field=models.BooleanField(default=False),
        ),
    ]
