# Generated by Django 5.0.1 on 2024-01-24 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_conversation_agent_conversation_agent_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
    ]
