# Generated by Django 5.0.1 on 2024-01-24 10:29

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_conversation_created_at_and_more"),
    ]

    operations = [
        TrigramExtension(),
    ]
