# Generated by Django 5.0.1 on 2024-01-24 11:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_auto_20240124_1029"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="text_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name_email_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["text_vector"], name="message_text_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_email_vector"], name="user_name_email_gin"
            ),
        ),
    ]
