# Generated by Django 5.0.1 on 2024-01-25 12:28

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_text_vector_user_name_email_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_email_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
