# Generated by Django 5.0.1 on 2024-01-25 14:00

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = get_user_model()
    # Creating a superuser
    superuser = User.objects.create(
        username='admin',
        email='admin@admin.com',
        password=make_password('admin'),  # Never store passwords in plain text
        is_superuser=True,
        is_staff=True,
        is_active=True
    )
    superuser.save()

class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_alter_message_text_vector_and_more"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
